employee Practice/hh/Employment-Project/Employment/src/App/Employment-Project.Frontend/Controllers/CityController.cs
using Employment_Project.Frontend.Contracts.Base;
using Employment_Project.Frontend.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Employment_Project.Frontend.Controllers;

public class CityController : Controller
{
    private readonly IEmploymentClient _employmentClient;
    public CityController(IEmploymentClient employmentClient)=> _employmentClient = employmentClient;
    public async Task<IActionResult> Index() => View(await _employmentClient.GetAllCity());
    [HttpGet]
    public async Task<IActionResult> AddorEdit(int id)
    {
        ViewData["stateId"] = await _employmentClient.StateDropdown();
        if (id == 0) return View(new City());
        else
        {
            var response = await _employmentClient.GetCityById(id);
            if (response != null) return View(response);
        }
        return View(new State());
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddorEdit(int id, City city)
    {
        if (ModelState.IsValid)
        {
            if (id == 0)
            {
                //save data
                if (ModelState.IsValid)
                {
                    await _employmentClient.AddCity(city);
                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                //UPDATE//
                if (ModelState.IsValid)
                {
                    await _employmentClient.UpdateCity(id, city);
                    return RedirectToAction(nameof(Index));
                }
                return View(city);
            }
        }
        return View(new City());
    }

    public async Task<IActionResult> Delete(int id)
    {
        await _employmentClient.DeleteCity(id);
        return RedirectToAction(nameof(Index));
    }
}

employee Practice/hh/Employment-Project/Employment/src/App/Employment-Project.Frontend/Controllers/CountryController.cs
using Employment_Project.Frontend.Contracts.Base;
using Employment_Project.Frontend.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Employment_Project.Frontend.Controllers;

public class CountryController : Controller
{
    private IEmploymentClient _employmentClient;
    public CountryController(IEmploymentClient  employmentClient) => _employmentClient = employmentClient;
    public async Task<IActionResult> Index() => View(await _employmentClient.GetAllCountry());
    [HttpGet]
    public async Task<IActionResult> AddorEdit(int id)
    {
        if (id == 0) return View(new Country());
        else
        {
            var data = await _employmentClient.GetCountryById(id);
            return View(data);
        }
    }
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> AddorEdit(Country country, int id)
    {
        if (ModelState.IsValid)
        {
            if (id == 0)
            {
                //Save//
                await _employmentClient.AddCountry(country);
                return RedirectToAction(nameof(Index));
            }
            else
            {         //Update
                if (ModelState.IsValid)
                {
                    await _employmentClient.UpdateCountry(id, country);
                    return RedirectToAction(nameof(Index));
                }
                return View(country);
            }
        }
        return View(new Country());
    }
    public async Task<ActionResult> Delete(int id)
    {
        await _employmentClient.DeleteCountry(id);
        return RedirectToAction(nameof(Index));
    }
}

employee Practice/hh/Employment-Project/Employment/src/App/Employment-Project.Frontend/Controllers/EmployeeController.cs
using Employment_Project.Frontend.Contracts.Base;
using Employment_Project.Frontend.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace Employment_Project.Frontend.Controllers;

public class EmployeeController : Controller
{
    private readonly IEmploymentClient _employmentClient;

    public EmployeeController(IEmploymentClient employmentClient)
    {
        _employmentClient = employmentClient;
    }

    public async Task<IActionResult> Index() => View(await _employmentClient.GetAllEmployee());

    [HttpGet]
    public async Task<IActionResult> AddorEdit(int id)
    {
        ViewData["stateId"] = await _employmentClient.StateDropdown();
        ViewData["cityId"] = await _employmentClient.CityDropdown();
        ViewData["countryId"] = await _employmentClient.CountryDropdown();
        ViewData["departmentId"] = await _employmentClient.DepartmentDropdown();
        if (id == 0) return View(new Employee());
        else
        {
            var response = await _employmentClient.GetEmployeeById(id);
            if (response != null) return View(response);
        }
        return View(new Employee());
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddorEdit(int id, [FromForm] Employee employee)
    {
        if (ModelState.IsValid)
        {
            if (id == 0)
            {
                //save data
                if (ModelState.IsValid)
                {
                   await _employmentClient.AddEmployee(employee);
                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                //UPDATE//
                if (ModelState.IsValid)
                {
                    await _employmentClient.UpdateEmployee(id, employee);
                    return RedirectToAction(nameof(Index));
                }
                return View(employee);
            }
        }
        return View(new Employee());
    }

    public async Task<IActionResult> Delete(int id)
    {
        await _employmentClient.DeleteEmployee(id);
        return RedirectToAction(nameof(Index));
    }
}

employee Practice/hh/Employment-Project/Employment/src/App/Employment-Project.Frontend/Controllers/StateController.cs
using Employment_Project.Frontend.Contracts.Base;
using Employment_Project.Frontend.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Employment_Project.Frontend.Controllers;

public class StateController : Controller
{
    private readonly IEmploymentClient _employmentClient;

    public StateController(IEmploymentClient employmentClient)
    {
        _employmentClient = employmentClient;
    }

    public async Task<IActionResult> Index() => View(await _employmentClient.GetAllState());

    [HttpGet]
    public async Task<IActionResult> AddorEdit(int id)
    {
        ViewData["CountryId"] = await _employmentClient.CountryDropdown();
        if (id == 0) return View(new State());
        else
        {
            var response = await _employmentClient.GetStateById(id);
            if (response != null) return View(response);
        }
        return View(new State());
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddorEdit(int id, State state)
    {
        if (ModelState.IsValid)
        {
            if (id == 0)
            {
                //save data
                if (ModelState.IsValid)
                {
                    await _employmentClient.AddState(state);
                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                //UPDATE//
                if (ModelState.IsValid)
                {
                    await _employmentClient.UpdateState(id, state);
                    return RedirectToAction(nameof(Index));
                }
                return View(state);
            }
        }

        return View(new State());
    }

    public async Task<IActionResult> Delete(int id)
    {
        await _employmentClient.DeleteState(id);
        return RedirectToAction(nameof(Index));
    }
}

employee Practice/hh/Employment-Project/Employment/src/App/Employment-Project.Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
  
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employment_Project.Frontend</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Country</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="State" asp-action="Index">State</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="index">City</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="index">Employee</a>
                        </li> 


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Employment_Project.Frontend - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>