MVC_PROJECT_PRACTICE/MVC_PROJECT_PRACTICE/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_PROJECT_PRACTICE.DBCon;
using MVC_PROJECT_PRACTICE.Models;

namespace MVC_PROJECT_PRACTICE.Controllers
{
    public class TeacherController : Controller
    {
        private readonly DbConnectionContext _context;
        public TeacherController(DbConnectionContext context)
        {
            _context = context;
        }
        public async Task<ActionResult> TeacherIndex()
        {
            var data = await _context.TeacherDetails.ToListAsync();
            return View(data);
        }

        public ActionResult TeacherCreate()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> TeacherCreate(Teacher teacher)
        {
            if (!ModelState.IsValid)
            {
                return View(teacher);
            }

            teacher.CreatedAt = DateTime.Now.ToString();
            teacher.UpdatedAt = DateTime.Now.ToString();
            teacher.UpdatedBy = "Monaem";
            teacher.CreatedBy = "Monaem";

            await _context.TeacherDetails.AddAsync(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction("TeacherIndex");
        }
    }
}

MVC_PROJECT_PRACTICE/MVC_PROJECT_PRACTICE/Controllers/ThesisController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_PROJECT_PRACTICE.DBCon;
using MVC_PROJECT_PRACTICE.Models;

namespace MVC_PROJECT_PRACTICE.Controllers
{
    public class ThesisController : Controller
    {
        private readonly DbConnectionContext _context;
        public ThesisController(DbConnectionContext context)
        {
            _context = context;
        }

        public async Task<ActionResult> ThesisIndex()
        {
            var data = await _context.ThesisDetails.Include(x=>x.Teacher).Include(x=>x.Student).ToListAsync();
            foreach(var item in data)
            {
                var teacher = await _context.TeacherDetails.FindAsync(item.ThesisTeacherId);
                item.Teacher = teacher;

                var student = await _context.StudentDetails.FindAsync(item.ThesisStudentId);
                item.Student = student;
            }
            return View(data);
        }

        public ActionResult ThesisCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> ThesisCreate(Thesis thesis)
        {
            if (!ModelState.IsValid)
            {
                return View(thesis);
            }

            thesis.CreatedAt = DateOnly.FromDateTime(DateTime.UtcNow).ToString();
            thesis.UpdatedAt = DateOnly.FromDateTime(DateTime.UtcNow).ToString();
            thesis.UpdatedBy = "Monaem";
            thesis.CreatedBy = "Monaem";

            await _context.ThesisDetails.AddAsync(thesis);
            await _context.SaveChangesAsync();
            return RedirectToAction("ThesisIndex");
        }
    }
}

MVC_PROJECT_PRACTICE/MVC_PROJECT_PRACTICE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_PROJECT_PRACTICE.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" asp-append-version="true">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <div>
                        <img src="~/Monaem khan logo.png" alt="" width="100px">
                    </div>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 fs-4">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page">@ViewData["Role"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Privacy">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle active" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Other Links
                            </a>
                            <ul class="dropdown-menu fs-4" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Student" asp-action="StudentIndex">Student Details</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Teacher" asp-action="TeacherIndex">Teacher Details</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Thesis" asp-action="ThesisIndex">Thesis Details</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVC_PROJECT_PRACTICE - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>